### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: ./pretrained_model/Meta-Llama-3-8B
adapter_name_or_path: ./saves/lora/sft/checkpoint-8000
template: llama3
finetuning_type: lora

### export
export_dir: ./saves/lora/sft/checkpoint-8000-merged
export_size: 2
export_device: cpu
export_legacy_format: false
