### model
model_name_or_path: /media/2/yx/model_cache/Meta-Llama-3-8B

### method
stage: sft
do_train: true
do_eval: false
do_predict: false
finetuning_type: lora
lora_target: q_proj, k_proj, v_proj, o_proj, up_proj, down_proj, gate_proj

### dataset
dataset_dir: LLaMA-Factory/data
dataset: BeaverTails_safe
template: llama3
cutoff_len: 1024
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/lora/sft
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 50.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true

### eval
#val_size: 0.1
#per_device_eval_batch_size: 4
#evaluation_strategy: steps
#eval_steps: 500

##logging
report_to: wandb # ['tensorboard', 'wandb', 'mlflow', 'none']
run_name: alignment-sft
