### model
model_name_or_path: ./saves/lora/sft/checkpoint-8000-merged

### method
stage: dpo
do_train: true
do_eval: false
do_predict: false
finetuning_type: lora
lora_target: q_proj, k_proj, v_proj, o_proj, up_proj, down_proj, gate_proj
pref_beta: 2.0
simpo_gamma: 1.0
pref_loss: simpo  # [sigmoid (dpo), orpo, simpo]

### dataset
dataset_dir: ./LLaMA_Factory/data
dataset: BeaverTails_preference
template: safety_llama3
cutoff_len: 1024
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/lora/simpo
logging_steps: 10
save_steps: 250
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true

### eval
#val_size: 0.1
#per_device_eval_batch_size: 1
#evaluation_strategy: steps
#eval_steps: 500

##logging
report_to: wandb # ['tensorboard', 'wandb', 'mlflow', 'none']
run_name: alignment-simpo